
[package]
name = "tac"
version = "0.1.0"
edition = "2021"

[dependencies]
ncurses = { version = "5.101", features = ["wide"] }
chrono  = "0.4"
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }
libc = "0.2"
shellexpand = "2.1"
serde_json = "1.0"
